openapi: 3.0.0
info:
  title: User and Post API
  version: 1.0.0
paths:
  /api/users/{id}:
    get:
      summary: Get user profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update user profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/posts:
    get:
      summary: Get posts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCreate'
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /api/posts/{id}:
    put:
      summary: Update a post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUpdate'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    delete:
      summary: Delete a post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        email:
          type: string
        bio:
          type: string
        avatar:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    UserUpdate:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        bio:
          type: string
        avatar:
          type: string
    Post:
      type: object
      properties:
        _id:
          type: string
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
        image:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    PostCreate:
      type: object
      properties:
        content:
          type: string
        image:
          type: string
    PostUpdate:
      type: object
      properties:
        content:
          type: string
        image:
          type: string